// This file is auto-generated by ts-scripts/generate-new-migration.ts
// Do not edit this file manually
// To add a new migration, run 'yarn generate-migration <migration name>'
import { RealmMigration } from "../migrations/types";

import { migrationTestMigration1699132034386 } from "./1699132034386-test-migration";
export const migrations: RealmMigration[] = [
  migrationTestMigration1699132034386,
];
